[package]
name = "selection_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-set = "0.5.3"
clap = { version = "4.4.7", features = ["derive"] }
hashbrown = { version = "0.14.2", features = ["serde"] }
indicatif = "0.17.7"
nauty-Traces-sys = { version = "0.7.0", features = ["native"] }
postcard = { version = "1.0.8", features = ["use-std"] }
serde = "1.0.189"

[profile.release]
debug = true
# lto = true
